version: '3'
services:
  webserver:
    container_name: laravel-google-captcha-examples-database-webserver
    build:
      context: .
      dockerfile: .docker/Dockerfile-webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./public/:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      DB_HOST: laravel-google-captcha-examples-database
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
      DB_DATABASE: laravel

  database:
    container_name: laravel-google-captcha-examples-database
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: laravel
